# Generated by Django 5.0 on 2023-12-08 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='место')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='время')),
                ('action', models.TextField(blank=True, null=True, verbose_name='действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='приятная привычка')),
                ('frequency', models.PositiveIntegerField(default=1, verbose_name='периодичность')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='награда')),
                ('completion_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='время на выполнение(минуты)')),
                ('is_public', models.BooleanField(default=False, verbose_name='публичная привычка')),
                ('related_pleasant_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit_tracker.habit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель привычки')),
            ],
        ),
    ]
